### ISSUE TITLE
Create screen and add title for My Shots

### ISSUE THREAD

**Issue by ashiswin** [ashiswin/bird-watching#2]
# Background
We need a new screen for the user's personal photo gallery. This will be hosted on the My Shots page.

# Todo
- [ ] Create a new screen for My Shots
- [ ] Register screen with Tab Bar
- [ ] Add title with proper positioning and style
